name = "my-telegram-bot"
compatibility_date = "2024-09-10"
compatibility_flags = ["nodejs_compat"]

[vars]
BACKEND_URL = "https://my-telegram-bot-backend.onrender.com"

[[kv_namespaces]]
binding = "BOT_CACHE"
id = "e36381297185476bab10075a241b7ca1"