name = "my-telegram-bot"
main = "src/index.js"
compatibility_date = "2024-01-01"

kv_namespaces = [
  { binding = "BOT_CACHE", id = "e36381297185476bab10075a241b7ca1" }
]

# Add this for ES modules
compatibility_flags = ["nodejs_compat"]

